[project]
name = "gans"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "medmnist>=3.0.2",
    "tqdm>=4.67.1",
]
